const type = 'WORKER';

export default  {
  SET_START_LOADING_ACTION: `${type}:SET_START_LOADING_ACTION`,
  GET_DATA_FROM_API_REQUEST: `${type}:GET_DATA_FROM_API_REQUEST`,
  GET_DATA_FROM_API_SUCCESS: `${type}:GET_DATA_FROM_API_SUCCESS`,
  GET_DATA_FROM_API_ERROR: `${type}:GET_DATA_FROM_API_ERROR`,
};
